# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CTP\CppCTP\FutureTools\Eric_Design\FutureTab.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FutureTab(object):
    def setupUi(self, FutureTab):
        FutureTab.setObjectName(_fromUtf8("FutureTab"))
        FutureTab.resize(950, 500)
        self.horizontalLayout = QtGui.QHBoxLayout(FutureTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableWidget = QtGui.QTableWidget(FutureTab)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(21)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(14, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(15, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(16, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(17, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(17, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(17, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(18, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(18, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(18, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(19, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(19, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(19, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(20, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(20, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(20, 3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)

        self.retranslateUi(FutureTab)
        QtCore.QMetaObject.connectSlotsByName(FutureTab)

    def retranslateUi(self, FutureTab):
        FutureTab.setWindowTitle(_translate("FutureTab", "交易所页面", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("FutureTab", "新建行", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("FutureTab", "1", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("FutureTab", "2", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("FutureTab", "3", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("FutureTab", "4", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("FutureTab", "5", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("FutureTab", "6", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("FutureTab", "7", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("FutureTab", "8", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("FutureTab", "9", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("FutureTab", "10", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("FutureTab", "11", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("FutureTab", "12", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("FutureTab", "13", None))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("FutureTab", "14", None))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("FutureTab", "15", None))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("FutureTab", "16", None))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("FutureTab", "17", None))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("FutureTab", "18", None))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("FutureTab", "19", None))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("FutureTab", "20", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FutureTab", "公告ID", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FutureTab", "交易所公告", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FutureTab", "发布时间", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FutureTab", "阅读否", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FutureTab = QtGui.QWidget()
    ui = Ui_FutureTab()
    ui.setupUi(FutureTab)
    FutureTab.show()
    sys.exit(app.exec_())

